// Auto-generated by @tailor-platform/app-shell-vite-plugin
// Do not edit manually
/* eslint-disable @typescript-eslint/no-empty-object-type */

import { createTypedPaths } from "@tailor-platform/app-shell";

/**
 * Route parameter definitions for file-based routing.
 * Maps route paths to their required parameters.
 *
 * This type is automatically generated and updated by the app-shell vite plugin
 * during `vite build` or `vite dev`. The plugin scans your pages directory
 * and generates entries for each route based on your file structure.
 *
 * Do not edit this file manually - your changes will be overwritten.
 */
export type GeneratedRouteParams = {
  "/": {};
  "/dashboard": {};
  "/dashboard/orders": {};
  "/dashboard/orders/:id": { id: string };
  "/settings": {};
};

/**
 * Type-safe path builder for navigating between routes.
 *
 * @example
 * ```tsx
 * import { paths } from "./routes.generated";
 *
 * // Static route
 * paths.for("/dashboard"); // → "/dashboard"
 *
 * // Dynamic route with parameters
 * paths.for("/orders/:id", { id: "123" }); // → "/orders/123"
 *
 * // With query string
 * paths.for("/orders/:id?tab=details", { id: "123" }); // → "/orders/123?tab=details"
 *
 * // Usage with navigation
 * const navigate = useNavigate();
 * navigate(paths.for("/orders/:id", { id: orderId }));
 *
 * // Usage with Link component
 * <Link to={paths.for("/dashboard")}>Dashboard</Link>
 * ```
 */
export const paths = createTypedPaths<GeneratedRouteParams>();

/**
 * Module augmentation for app-shell's type system.
 *
 * This augmentation registers the generated route parameters with app-shell,
 * allowing other app-shell features to reference these types.
 *
 * @example
 * ```tsx
 * import type { RouteParams } from "@tailor-platform/app-shell";
 *
 * // RouteParams is now typed as GeneratedRouteParams
 * type MyRoutes = keyof RouteParams; // "/", "/dashboard", "/orders/:id", etc.
 * ```
 */
declare module "@tailor-platform/app-shell" {
  interface AppShellRegister {
    routeParams: GeneratedRouteParams;
  }
}
