import type { ReactNode } from "react";
import type { FilterConfig, SortConfig, TableFieldName, TableMetadata } from "@/types/collection";
import { fieldTypeToFilterConfig, fieldTypeToSortConfig } from "@/types/collection";
import type { Column, MetadataFieldOptions } from "./types";

// =============================================================================
// column() helper
// =============================================================================

/**
 * Define a column with explicit render and optional sort/filter/accessor.
 * Prefer {@link createColumnHelper} to bind `TRow` once at the helper level.
 */
export function column<TRow extends Record<string, unknown>>(options: Column<TRow>): Column<TRow> {
  return {
    label: options.label,
    render: options.render,
    id: options.id,
    width: options.width,
    accessor: options.accessor,
    sort: options.sort,
    filter: options.filter,
  };
}

// =============================================================================
// inferColumns() — metadata-driven column defaults
// =============================================================================

function formatValue(value: unknown): ReactNode {
  if (value == null) return "";
  if (typeof value === "boolean") return value ? "✓" : "✗";
  if (value instanceof Date) return value.toLocaleDateString();
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

/**
 * Return a function that produces `Column` from metadata field names.
 * Prefer {@link createColumnHelper} to bind `TRow` once at the helper level.
 */
export function inferColumns<
  TRow extends Record<string, unknown>,
  const TTable extends TableMetadata = TableMetadata,
>(tableMetadata: TTable): ColumnInferFn<TRow, TTable> {
  const fields = tableMetadata.fields;

  return (dataKey: TableFieldName<TTable>, columnOptions?: MetadataFieldOptions): Column<TRow> => {
    const fieldName = dataKey as string;
    const fieldMeta = fields.find((f) => f.name === fieldName);
    if (!fieldMeta) {
      throw new Error(`Field "${fieldName}" not found in table "${tableMetadata.name}" metadata`);
    }

    let sort: SortConfig | undefined;
    if (columnOptions?.sort !== false) {
      sort = fieldTypeToSortConfig(fieldName, fieldMeta.type);
    }

    let filter: FilterConfig | undefined;
    if (columnOptions?.filter !== false) {
      filter = fieldTypeToFilterConfig(fieldName, fieldMeta.type, fieldMeta.enumValues);
    }

    const label = columnOptions?.label ?? fieldMeta.description ?? fieldMeta.name;

    return {
      label,
      render: ((row: Record<string, unknown>) => formatValue(row[fieldName])) as (
        row: TRow,
      ) => ReactNode,
      accessor: ((row: Record<string, unknown>) => row[fieldName]) as (row: TRow) => unknown,
      width: columnOptions?.width,
      sort,
      filter,
    };
  };
}

// =============================================================================
// createColumnHelper() — factory with TRow bound once
// =============================================================================

/**
 * Per-field column factory returned by `inferColumns(tableMetadata)`.
 *
 * Derives label, sort config, and filter config from the field's metadata.
 * Sort and filter can be suppressed per call via `options`.
 *
 * @param dataKey - A field name from the bound table metadata.
 * @param options - Optional per-column overrides (label, width, sort, filter).
 * @throws {Error} If `dataKey` is not found in the metadata passed to `inferColumns`.
 */
export type ColumnInferFn<
  TRow extends Record<string, unknown>,
  TTable extends TableMetadata = TableMetadata,
> = (dataKey: TableFieldName<TTable>, options?: MetadataFieldOptions) => Column<TRow>;

/**
 * Object returned by `createColumnHelper`.
 */
export interface ColumnHelper<TRow extends Record<string, unknown>> {
  /**
   * Define a column with an explicit render function.
   *
   * @example
   * ```tsx
   * column({ label: "Name", render: (row) => row.name })
   * column({ label: "Actions", render: (row) => <button>Edit {row.name}</button> })
   * ```
   */
  column: (options: Column<TRow>) => Column<TRow>;
  /**
   * Bind table metadata once and return a per-field column factory.
   *
   * The returned factory **throws at call time** if the given field name is not
   * found in `tableMetadata`. This typically happens at module initialisation
   * (i.e. when columns are defined outside a component), so it surfaces as an
   * uncaught error rather than a render error. Field-name narrowing is only
   * active when `tableMetadata` is typed from an `as const` source (e.g. a
   * file generated by `appShellMetadataPlugin`).
   *
   * @throws {Error} If the field name is not found in the provided table metadata.
   *
   * @example
   * ```tsx
   * const infer = inferColumns(tableMetadata.order);
   * const columns = [
   *   column(infer("title")),
   *   column({
   *     ...infer("status"),
   *     render: (row) => <StatusBadge value={row.status} />
   *   }),
   * ];
   * ```
   */
  inferColumns: <const TTable extends TableMetadata = TableMetadata>(
    tableMetadata: TTable,
  ) => ColumnInferFn<TRow, TTable>;
}

/**
 * Factory that captures the row type once and returns `column` and `inferColumns`
 * with `TRow` already bound.
 *
 * @example
 * ```tsx
 * const { column, inferColumns } = createColumnHelper<Order>();
 *
 * const infer = inferColumns(tableMetadata.order);
 * const columns = [
 *   column(infer("title")),
 *   column({ label: "Actions", render: (row) => <button>Edit {row.name}</button> }),
 * ];
 * ```
 */
export function createColumnHelper<TRow extends Record<string, unknown>>(): ColumnHelper<TRow> {
  return {
    column: (options: Column<TRow>) => column<TRow>(options),
    inferColumns: <const TTable extends TableMetadata = TableMetadata>(tableMetadata: TTable) =>
      inferColumns<TRow, TTable>(tableMetadata),
  };
}
