import type { FC, ReactNode } from "react";
import type { Guard, LoaderHandler } from "@/resource";
import type { LocalizedString } from "@/lib/i18n";

// ============================================
// Page Component Types
// ============================================

/**
 * Props that can be attached to a page component via static field.
 *
 * @example
 * ```tsx
 * const DashboardPage = () => <div>Dashboard</div>;
 *
 * DashboardPage.appShellPageProps = {
 *   meta: { title: "Dashboard", icon: <DashboardIcon /> },
 *   guards: [authGuard],
 * } satisfies AppShellPageProps;
 *
 * export default DashboardPage;
 * ```
 */
export type AppShellPageProps = {
  /**
   * Metadata for the page used in navigation and breadcrumbs.
   */
  meta?: {
    /**
     * Title of the page displayed in navigation and breadcrumbs.
     * Supports localized strings with translations.
     */
    title?: LocalizedString;
    /**
     * Icon displayed alongside the title in navigation.
     */
    icon?: ReactNode;
  };

  /**
   * Guards to control access to this page.
   * Guards are executed in order. Each page must define its own guards explicitly.
   *
   * @example
   * ```tsx
   * guards: [authGuard, adminGuard]
   * ```
   */
  guards?: Guard[];

  /**
   * Loader function to fetch data before rendering the page.
   */
  loader?: LoaderHandler;
};

/**
 * A React component that can be used as a page in file-based routing.
 *
 * The component can optionally have an `appShellPageProps` static field
 * for configuring navigation metadata, guards, and loaders.
 */
export type PageComponent = FC & {
  appShellPageProps?: AppShellPageProps;
};

// ============================================
// Virtual Module Types
// ============================================

/**
 * A page entry generated by the Vite plugin from file system.
 */
export type PageEntry = {
  /**
   * The resolved path for this page (e.g., "/dashboard/orders/:id")
   */
  path: string;
  /**
   * The page component with optional appShellProps
   */
  component: PageComponent;
};

/**
 * Output type for the virtual:app-shell-pages module.
 */
export type VirtualPagesModule = {
  pages: PageEntry[];
};

// ============================================
// Vite Plugin Options
// ============================================

/**
 * Validation level for appShellPageProps schema checking.
 */
export type ValidationLevel = "warn" | "error" | "off";

/**
 * Options for the appShellRoutes Vite plugin.
 */
export type AppShellRoutesPluginOptions = {
  /**
   * Directory containing page files.
   * @default "src/pages"
   */
  pagesDir?: string;

  /**
   * Enable debug logging to see scanned pages and generated code.
   * @default false
   */
  debug?: boolean;

  /**
   * Validation options for appShellPageProps schema.
   */
  validation?: {
    /**
     * Whether validation is enabled.
     * @default true
     */
    enabled?: boolean;

    /**
     * How to handle validation errors.
     * - "warn": Output warning and continue build (default)
     * - "error": Output error and fail build
     * - "off": Disable validation
     * @default "warn"
     */
    level?: ValidationLevel;
  };
};

// ============================================
// Path Conversion Types
// ============================================

/**
 * Segment types for path conversion.
 */
export type PathSegmentType =
  | "static" // Regular path segment (e.g., "orders")
  | "dynamic" // Dynamic parameter (e.g., "[id]" -> ":id")
  | "catchAll" // Catch-all parameter (e.g., "[...slug]" -> "*slug")
  | "group" // Route group (e.g., "(admin)" -> excluded from path)
  | "ignored"; // Ignored segment (e.g., "_lib" -> excluded from routing)

/**
 * Parsed path segment information.
 */
export type ParsedSegment = {
  type: PathSegmentType;
  /**
   * Original directory name
   */
  original: string;
  /**
   * Converted segment for routing (empty for groups)
   */
  converted: string;
};
