/**
 * Type-safe path builder for file-based routing.
 *
 * This module provides a factory function to create type-safe path builders
 * that work with auto-generated route type definitions.
 *
 * @example
 * ```ts
 * // In routes.generated.ts (auto-generated by vite-plugin)
 * import { createTypedPaths } from "@tailor-platform/app-shell";
 *
 * type RouteParams = {
 *   "/": {};
 *   "/dashboard": {};
 *   "/orders/:id": { id: string };
 * };
 *
 * export const paths = createTypedPaths<RouteParams>();
 *
 * // Usage
 * paths.for("/orders/:id", { id: "123" }); // → "/orders/123"
 * paths.for("/orders/:id?tab=details", { id: "123" }); // → "/orders/123?tab=details"
 * ```
 */

// ============================================
// Type Utilities
// ============================================

/**
 * Extract base path (before ?) from a path that may include query string.
 */
type ExtractBasePath<T extends string> = T extends `${infer Base}?${string}`
  ? Base
  : T;

/**
 * Check if an object type has no keys.
 */
type IsEmptyObject<T> = keyof T extends never ? true : false;

// ============================================
// TypedPaths Interface
// ============================================

/**
 * Type-safe path builder interface.
 *
 * @typeParam TRoutes - Mapping of route paths to their parameter types
 */
type TypedPaths<TRoutes extends Record<string, Record<string, string>>> = {
  /**
   * Build a URL path with type-checked parameters.
   *
   * @param path - Route path template (can include ?query suffix)
   * @param params - Path parameters (required if route has dynamic segments)
   * @returns Resolved URL path string
   *
   * @example
   * ```ts
   * // Static route
   * paths.for("/dashboard"); // → "/dashboard"
   *
   * // Dynamic route
   * paths.for("/orders/:id", { id: "123" }); // → "/orders/123"
   *
   * // With query string
   * paths.for("/items/:id?tab=details", { id: "456" }); // → "/items/456?tab=details"
   * ```
   */
  for<
    T extends (keyof TRoutes & string) | `${keyof TRoutes & string}?${string}`,
  >(
    path: T,
    ...params: ExtractBasePath<T> extends keyof TRoutes
      ? IsEmptyObject<TRoutes[ExtractBasePath<T>]> extends true
        ? []
        : [TRoutes[ExtractBasePath<T>]]
      : never
  ): string;
};

// ============================================
// Factory Function
// ============================================

/**
 * Create a type-safe path builder from route definitions.
 *
 * This factory is designed to work with auto-generated RouteParams types
 * from the vite-plugin's `generateTypedRoutes` option.
 *
 * @typeParam TRoutes - Mapping of route paths to their parameter types
 * @returns TypedPaths instance with `for()` method
 *
 * @example
 * ```ts
 * type RouteParams = {
 *   "/dashboard": {};
 *   "/orders/:id": { id: string };
 *   "/orders/:orderId/items/:itemId": { orderId: string; itemId: string };
 * };
 *
 * const paths = createTypedPaths<RouteParams>();
 *
 * paths.for("/dashboard"); // ✅
 * paths.for("/orders/:id", { id: "123" }); // ✅
 * paths.for("/orders/:id"); // ❌ TypeScript error: params required
 * paths.for("/invalid"); // ❌ TypeScript error: path not found
 * ```
 */
export function createTypedPaths<
  TRoutes extends Record<string, Record<string, string>>,
>(): TypedPaths<TRoutes> {
  return {
    for(path, ...args) {
      const params = args[0] as Record<string, string> | undefined;
      if (!params) {
        return path;
      }

      // Replace :param and *param patterns with actual values
      return path.replace(/:([^/?]+)|\*([^/?]+)/g, (_, dynamic, catchAll) => {
        if (dynamic) {
          // Dynamic segment: encode the entire value
          return encodeURIComponent(params[dynamic] ?? "");
        }
        // Catch-all segment: encode each path segment individually, preserve slashes
        const value = params[catchAll] ?? "";
        return value
          .split("/")
          .map((segment) => encodeURIComponent(segment))
          .join("/");
      });
    },
  };
}
