packages:
  - examples/**
  - packages/**

catalog:
  eslint: ^9.0.0
  "@eslint/js": ^9.39.2
  eslint-plugin-react-hooks: ^7.0.1
  globals: ^15.15.0
  typescript-eslint: ^8.55.0
  "@types/react": ^19
  "@types/react-dom": ^19
  "@vitejs/plugin-react": ^5.1.2
  vite: ^7.3.1
