// GENERATED by docs-kit — do not edit by hand.
import type { AppShellPageProps } from "@tailor-platform/app-shell";

import { DocPage } from "../../../_lib/DocPage";

const Page = () => <DocPage slug="modules-and-resources" />;

Page.appShellPageProps = {
  meta: { title: "Modules and Resources" },
} satisfies AppShellPageProps;

export default Page;
