// This file is auto-generated by @tailor-platform/sdk
// Do not edit this file manually
// Regenerated automatically when running 'tailor deploy' or 'tailor generate'

declare module "@tailor-platform/sdk" {
  interface Attributes {
    roles: string[];
  }
  interface AttributeList {
    __tuple?: [];
  }
  interface Env {}
  interface MachineUserNameRegistry {}
  interface IdpNameRegistry {
    "e2e-idp": true;
  }
  interface ConnectionNameRegistry {}
  interface AIGatewayNameRegistry {
    "e2e-ai-gateway": true;
  }
  interface AuthNamespaceNameRegistry {
    "e2e-auth": true;
  }
}

export {};
