// This file is auto-generated by @tailor-platform/sdk
// Do not edit this file manually
// Regenerated automatically when running 'tailor-sdk apply' or 'tailor-sdk generate'

declare module "@tailor-platform/sdk" {
  interface AttributeMap {
    roles: string[];
  }
  interface AttributeList {
    __tuple?: [];
  }
  interface Env {}
  interface MachineUserNameRegistry {}
  interface IdpNameRegistry {
    "e2e-idp": true;
  }
}

export {};
