import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import type { DocsConfig, Outline } from "./types";

function titleCase(slug: string): string {
  return slug
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/** Repo-relative path of a unit's generated route stub, or null when no
 * `pagesDir` is configured. The category is the unit's outDir minus its `docs/`
 * prefix (`docs/components` → `components`), so the browser route mirrors the
 * published doc tree. */
export function pagePathFor(outline: Outline, config: DocsConfig): string | null {
  if (!config.pagesDir) return null;
  const category = outline.outDir.replace(/^docs\//, "");
  return `${config.pagesDir}/${category}/${outline.slug}/page.tsx`;
}

/** The docs-browser mounts each unit's generated markdown through a tiny
 * `DocPage` route stub. It is pure glue — slug + title — so sync regenerates it
 * on every run and it must never be hand-edited. `DocPage` lives at
 * `<pagesDir>/../_lib/DocPage`, so the relative import depth follows the
 * category nesting. */
function renderPageStub(outline: Outline, config: DocsConfig): string {
  const category = outline.outDir.replace(/^docs\//, "");
  const toLib = "../".repeat(category.split("/").length + 2) + "_lib/DocPage";
  const title = outline.frontmatter.title ?? titleCase(outline.slug);
  return (
    `// GENERATED by docs-kit — do not edit by hand.\n` +
    `import type { AppShellPageProps } from "@tailor-platform/app-shell";\n\n` +
    `import { DocPage } from "${toLib}";\n\n` +
    `const Page = () => <DocPage slug="${outline.slug}" />;\n\n` +
    `Page.appShellPageProps = {\n` +
    `  meta: { title: ${JSON.stringify(title)} },\n` +
    `} satisfies AppShellPageProps;\n\n` +
    `export default Page;\n`
  );
}

/** Write a unit's route stub into the docs-browser and return its repo-relative
 * path (null when no `pagesDir` is configured). */
export function writePageStub(
  repoRoot: string,
  outline: Outline,
  config: DocsConfig,
): string | null {
  const rel = pagePathFor(outline, config);
  if (!rel) return null;
  const abs = join(repoRoot, rel);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, renderPageStub(outline, config), "utf8");
  return rel;
}
