import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { ReconciliationDetail } from "./ReconciliationDetail";
import { CommandPaletteProvider } from "../../contexts/command-palette-context";
import type { ReconciliationRecord, LineItemColumn } from "./types";
import type { FieldConfig } from "../description-card/types";

// ============================================================================
// TEST FIELD / COLUMN CONFIGS
// ============================================================================

const TEST_FIELDS: FieldConfig[] = [
  { key: "invoiceNumber", label: "Invoice Number" },
  { key: "supplier", label: "Supplier" },
  {
    key: "totalAmount",
    label: "Total Amount",
    type: "money",
    meta: { currencyKey: "currency" },
  },
  { key: "summary", label: "Summary", emptyBehavior: "hide" },
];

const TEST_COLUMNS: LineItemColumn[] = [
  { key: "lineNumber", header: "#" },
  { key: "product", header: "Product" },
  { key: "status", header: "Status", type: "badge", meta: { badgeVariantMap: { matched: "subtle-success", price_mismatch: "subtle-warning" } } },
  { key: "invoiceQty", header: "Inv Qty", type: "number", align: "right" },
  { key: "poQty", header: "PO Qty", type: "number", align: "right" },
  { key: "priceVariance", header: "Price Var", type: "variance", align: "right" },
];

// ============================================================================
// RENDER HELPER
// ============================================================================

const renderDetail = (props: React.ComponentProps<typeof ReconciliationDetail>) =>
  render(
    <CommandPaletteProvider>
      <ReconciliationDetail {...props} />
    </CommandPaletteProvider>,
  );

// ============================================================================
// MOCK DATA
// ============================================================================

const matchedRecord: ReconciliationRecord = {
  id: "1",
  status: "matched",
  matchScore: 100,
  data: {
    invoiceNumber: "26TKC-00200",
    supplier: "CADICA Tekstil VE Tic. Ltd. Sti.",
    totalAmount: 7854.01,
    currency: "USD",
    invoiceDate: new Date("2026-03-04"),
    summary: "All 2 line items matched successfully.",
  },
  summary: "All 2 line items matched successfully.",
  processingSteps: [
    { id: "s1", label: "Uploaded", status: "completed", timestamp: new Date("2026-04-07T19:20:00") },
    { id: "s2", label: "Extracted", status: "completed", timestamp: new Date("2026-04-07T19:21:17") },
    { id: "s3", label: "Matched", status: "completed", timestamp: new Date("2026-04-07T19:21:42") },
  ],
  discrepancies: [],
  lineItems: [
    { lineNumber: 1, product: "DVZA00677", status: "matched", invoiceQty: 35700, poQty: 35700, priceVariance: 0, currency: "USD" },
    { lineNumber: 2, product: "DVPU00316", status: "matched", invoiceQty: 1, poQty: 1, priceVariance: 0, currency: "USD" },
  ],
  relatedDocuments: [
    { id: "po-1", type: "purchase_order", label: "PO-105539", status: "Approved", statusVariant: "success", autoGenerated: false, href: "/purchase-orders/105539" },
    { id: "gr-1", type: "goods_receipt", label: "GR-200145", status: "Received", statusVariant: "success", autoGenerated: false, href: "/goods-receipts/200145" },
    { id: "bill-1", type: "purchase_bill", label: "BILL-003", status: "Draft", statusVariant: "warning", autoGenerated: true, href: "/purchase-bills/003" },
  ],
};

const partialMatchRecord: ReconciliationRecord = {
  ...matchedRecord,
  id: "2",
  status: "partial_match",
  matchScore: 75,
  data: {
    invoiceNumber: "SS26-0522",
    supplier: "Karmen Deri Urunleri Sanayi ve Ticaret A.S.",
    totalAmount: 157990.0,
    currency: "USD",
  },
  summary: "0/2 line items matched. 2 price discrepancies.",
  discrepancies: [
    { id: "d1", severity: "warning", category: "PRICE OVER PO", message: "Price mismatch for SS26OAL1144: Invoice=370, PO=365", resolved: false },
  ],
  lineItems: [
    { lineNumber: 1, product: "SS26OAL1144", status: "price_mismatch", invoiceQty: 417, poQty: 427, priceVariance: 1.4, currency: "USD" },
  ],
  relatedDocuments: [
    { id: "po-2", type: "purchase_order", label: "PO-105539", status: "Approved", statusVariant: "success", autoGenerated: false, href: "/purchase-orders/105539" },
  ],
};

const processingRecord: ReconciliationRecord = {
  ...matchedRecord,
  id: "3",
  status: "processing",
  matchScore: 0,
  data: { invoiceNumber: "NEW-001" },
  summary: "",
  processingSteps: [
    { id: "s1", label: "Uploaded", status: "completed", timestamp: new Date("2026-04-07T19:40:00") },
    { id: "s2", label: "Extracting", status: "in_progress" },
    { id: "s3", label: "Matching", status: "pending" },
  ],
  lineItems: [],
  discrepancies: [],
  relatedDocuments: [],
};

const lowScoreRecord: ReconciliationRecord = {
  ...partialMatchRecord,
  matchScore: 50,
  status: "mismatch",
};

const errorRecord: ReconciliationRecord = {
  ...matchedRecord,
  id: "err-1",
  status: "error",
  matchScore: 0,
  data: { invoiceNumber: "ERR-001" },
  summary: "OCR extraction failed — file corrupted.",
  lineItems: [],
  discrepancies: [],
  relatedDocuments: [],
};

// ============================================================================
// DEFAULT PROPS HELPER
// ============================================================================

function defaultProps(overrides: Partial<React.ComponentProps<typeof ReconciliationDetail>> & { data: ReconciliationRecord }) {
  return {
    fields: TEST_FIELDS,
    lineItemColumns: TEST_COLUMNS,
    ...overrides,
  };
}

afterEach(() => {
  cleanup();
});

describe("ReconciliationDetail", () => {
  describe("matched state", () => {
    it("renders DescriptionCard with match result title", () => {
      renderDetail(defaultProps({ data: matchedRecord }));
      expect(screen.getByText("Match Result")).toBeDefined();
    });

    it("renders data fields via DescriptionCard", () => {
      renderDetail(defaultProps({ data: matchedRecord }));
      expect(screen.getByText("26TKC-00200")).toBeDefined();
      expect(screen.getByText("CADICA Tekstil VE Tic. Ltd. Sti.")).toBeDefined();
    });

    it("renders summary field", () => {
      renderDetail(defaultProps({ data: matchedRecord }));
      expect(screen.getByText("All 2 line items matched successfully.")).toBeDefined();
    });

    it("renders line items comparison table", () => {
      renderDetail(defaultProps({ data: matchedRecord }));
      expect(screen.getByText("Line items comparison")).toBeDefined();
      expect(screen.getByText("DVZA00677")).toBeDefined();
      expect(screen.getByText("DVPU00316")).toBeDefined();
    });

    it("does not show discrepancies section when empty", () => {
      renderDetail(defaultProps({ data: matchedRecord }));
      expect(screen.queryByText("Discrepancies")).toBeNull();
    });

    it("renders related documents via LinkedRecordsCard", () => {
      renderDetail(defaultProps({ data: matchedRecord }));
      expect(screen.getAllByText(/PO-105539/).length).toBeGreaterThan(0);
      expect(screen.getAllByText(/GR-200145/).length).toBeGreaterThan(0);
    });

    it("hides ActionPanel when matched (no actions needed)", () => {
      renderDetail(defaultProps({ data: matchedRecord, onCreate: () => {}, onUpdate: () => {} }));
      expect(screen.queryByText("Create")).toBeNull();
      expect(screen.queryByRole("button", { name: "Update" })).toBeNull();
    });

    it("renders activity timeline", () => {
      renderDetail(defaultProps({ data: matchedRecord }));
      expect(screen.getByText("Activity")).toBeDefined();
    });
  });

  describe("score color coding", () => {
    it("shows green for scores >= 90", () => {
      renderDetail(defaultProps({ data: matchedRecord }));
      const score = screen.getByText(/100% Matched/);
      expect(score.className).toContain("green");
    });

    it("shows yellow for scores 70-89", () => {
      renderDetail(defaultProps({ data: partialMatchRecord }));
      const score = screen.getByText(/75% Partial Match/);
      expect(score.className).toContain("yellow");
    });

    it("shows red for scores < 70", () => {
      renderDetail(defaultProps({ data: lowScoreRecord }));
      const score = screen.getByText(/50% Mismatch/);
      expect(score.className).toContain("destructive");
    });
  });

  describe("partial match state", () => {
    it("renders discrepancies", () => {
      renderDetail(defaultProps({ data: partialMatchRecord }));
      expect(screen.getByText("Discrepancies")).toBeDefined();
      expect(screen.getByText(/PRICE OVER PO/)).toBeDefined();
    });

    it("shows ActionPanel with action buttons when partial match", async () => {
      const user = userEvent.setup();
      const onCreate = vi.fn();
      const onUpdate = vi.fn();

      renderDetail(defaultProps({ data: partialMatchRecord, onCreate, onUpdate }));

      await user.click(screen.getByText("Create"));
      expect(onCreate).toHaveBeenCalled();

      await user.click(screen.getByText("Update"));
      expect(onUpdate).toHaveBeenCalled();
    });

    it("shows variance colors in line items", () => {
      renderDetail(defaultProps({ data: partialMatchRecord }));
      const variance = screen.getByText("+1.4%");
      expect(variance.className).toContain("yellow");
    });
  });

  describe("processing state", () => {
    it("shows processing empty state", () => {
      renderDetail(defaultProps({ data: processingRecord }));
      expect(screen.getByText(/Processing/)).toBeDefined();
    });

    it("hides DescriptionCard during processing", () => {
      renderDetail(defaultProps({ data: processingRecord }));
      expect(screen.queryByText("NEW-001")).toBeNull();
    });

    it("hides line items and discrepancies when processing", () => {
      renderDetail(defaultProps({ data: processingRecord }));
      expect(screen.queryByText("Line items comparison")).toBeNull();
      expect(screen.queryByText("Discrepancies")).toBeNull();
    });

    it("auto-polls onRefresh at interval", () => {
      vi.useFakeTimers();
      const onRefresh = vi.fn();

      renderDetail(defaultProps({ data: processingRecord, onRefresh, refreshInterval: 3000 }));

      expect(onRefresh).not.toHaveBeenCalled();
      vi.advanceTimersByTime(3000);
      expect(onRefresh).toHaveBeenCalledTimes(1);
      vi.advanceTimersByTime(3000);
      expect(onRefresh).toHaveBeenCalledTimes(2);

      vi.useRealTimers();
    });

    it("does not poll when status is not processing", () => {
      vi.useFakeTimers();
      const onRefresh = vi.fn();

      renderDetail(defaultProps({ data: matchedRecord, onRefresh, refreshInterval: 3000 }));

      vi.advanceTimersByTime(10000);
      expect(onRefresh).not.toHaveBeenCalled();

      vi.useRealTimers();
    });
  });

  describe("error state", () => {
    it("shows error message instead of DescriptionCard", () => {
      renderDetail(defaultProps({ data: errorRecord }));
      expect(screen.getByText("OCR extraction failed — file corrupted.")).toBeDefined();
      expect(screen.queryByText("Match Result")).toBeNull();
    });

    it("shows retry action when onRefresh is provided", () => {
      renderDetail(defaultProps({ data: errorRecord, onRefresh: vi.fn() }));
      expect(screen.getByText("Retry processing")).toBeDefined();
    });

    it("hides Update and Create actions", () => {
      renderDetail(defaultProps({ data: errorRecord, onCreate: vi.fn(), onUpdate: vi.fn() }));
      expect(screen.queryByText("Create")).toBeNull();
      expect(screen.queryByText("Update")).toBeNull();
    });
  });

  it("matches snapshot (matched)", () => {
    const { container } = renderDetail(defaultProps({ data: matchedRecord }));
    expect(container.innerHTML).toMatchSnapshot();
  });

  it("matches snapshot (partial match)", () => {
    const { container } = renderDetail(
      defaultProps({ data: partialMatchRecord, onCreate: () => {}, onUpdate: () => {} }),
    );
    expect(container.innerHTML).toMatchSnapshot();
  });
});
