import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { ReconciliationDetail } from "./ReconciliationDetail";
import { CommandPaletteProvider } from "../../contexts/command-palette-context";
import type { ReconciliationRecord } from "./types";

// Wrap in CommandPaletteProvider (required by ActionPanel)
const renderDetail = (props: React.ComponentProps<typeof ReconciliationDetail>) =>
  render(
    <CommandPaletteProvider>
      <ReconciliationDetail {...props} />
    </CommandPaletteProvider>,
  );

// 🧪 Dummy Data
const matchedRecord: ReconciliationRecord = {
  id: "1",
  invoiceNumber: "26TKC-00200",
  status: "matched",
  matchScore: 100,
  supplier: "CADICA Tekstil VE Tic. Ltd. Sti.",
  totalAmount: 7854.01,
  currency: "USD",
  invoiceDate: new Date("2026-03-04"),
  createdAt: new Date("2026-04-07"),
  updatedAt: new Date("2026-04-07"),
  summary: "All 2 line items matched successfully.",
  processingSteps: [
    {
      id: "s1",
      label: "Uploaded",
      status: "completed",
      timestamp: new Date("2026-04-07T19:20:00"),
    },
    {
      id: "s2",
      label: "Extracted",
      status: "completed",
      timestamp: new Date("2026-04-07T19:21:17"),
    },
    { id: "s3", label: "Matched", status: "completed", timestamp: new Date("2026-04-07T19:21:42") },
  ],
  discrepancies: [],
  lineItems: [
    {
      lineNumber: 1,
      product: "DVZA00677",
      status: "matched",
      invoiceQty: 35700,
      poQty: 35700,
      grQty: 35700,
      qtyVariance: 0,
      invoicePrice: 0.22,
      poPrice: 0.22,
      priceVariance: 0,
      currency: "USD",
    },
    {
      lineNumber: 2,
      product: "DVPU00316",
      status: "matched",
      invoiceQty: 1,
      poQty: 1,
      grQty: 1,
      qtyVariance: 0,
      invoicePrice: 0.01,
      poPrice: 0.01,
      priceVariance: 0,
      currency: "USD",
    },
  ],
  relatedDocuments: [
    {
      id: "po-1",
      type: "purchase_order",
      label: "PO-105539",
      status: "Approved",
      statusVariant: "success",
      autoGenerated: false,
      href: "/purchase-orders/105539",
    },
    {
      id: "gr-1",
      type: "goods_receipt",
      label: "GR-200145",
      status: "Received",
      statusVariant: "success",
      autoGenerated: false,
      href: "/goods-receipts/200145",
    },
    {
      id: "bill-1",
      type: "purchase_bill",
      label: "BILL-003",
      status: "Draft",
      statusVariant: "warning",
      autoGenerated: true,
      href: "/purchase-bills/003",
    },
  ],
};

const partialMatchRecord: ReconciliationRecord = {
  ...matchedRecord,
  id: "2",
  invoiceNumber: "SS26-0522",
  status: "partial_match",
  matchScore: 75,
  supplier: "Karmen Deri Urunleri Sanayi ve Ticaret A.S.",
  totalAmount: 157990.0,
  summary: "0/2 line items matched. 2 price discrepancies.",
  discrepancies: [
    {
      id: "d1",
      severity: "warning",
      category: "PRICE OVER PO",
      message: "Price mismatch for SS26OAL1144: Invoice=370, PO=365",
      resolved: false,
    },
  ],
  lineItems: [
    {
      lineNumber: 1,
      product: "SS26OAL1144",
      status: "price_mismatch",
      invoiceQty: 417,
      poQty: 427,
      grQty: 427,
      qtyVariance: 0,
      invoicePrice: 370,
      poPrice: 365,
      priceVariance: 1.4,
      currency: "USD",
    },
  ],
  relatedDocuments: [
    {
      id: "po-2",
      type: "purchase_order",
      label: "PO-105539",
      status: "Approved",
      statusVariant: "success",
      autoGenerated: false,
      href: "/purchase-orders/105539",
    },
  ],
};

const processingRecord: ReconciliationRecord = {
  ...matchedRecord,
  id: "3",
  invoiceNumber: "NEW-001",
  status: "processing",
  matchScore: 0,
  summary: "",
  processingSteps: [
    {
      id: "s1",
      label: "Uploaded",
      status: "completed",
      timestamp: new Date("2026-04-07T19:40:00"),
    },
    { id: "s2", label: "Extracting", status: "in_progress" },
    { id: "s3", label: "Matching", status: "pending" },
  ],
  lineItems: [],
  discrepancies: [],
  relatedDocuments: [],
};

const lowScoreRecord: ReconciliationRecord = {
  ...partialMatchRecord,
  matchScore: 50,
  status: "mismatch",
};

afterEach(() => {
  cleanup();
});

describe("ReconciliationDetail", () => {
  describe("matched state", () => {
    it("renders DescriptionCard with match result title", () => {
      renderDetail({ data: matchedRecord });
      expect(screen.getByText("Match Result")).toBeDefined();
    });

    it("renders invoice number and supplier via DescriptionCard", () => {
      renderDetail({ data: matchedRecord });
      expect(screen.getByText("26TKC-00200")).toBeDefined();
      expect(screen.getByText("CADICA Tekstil VE Tic. Ltd. Sti.")).toBeDefined();
    });

    it("renders summary field", () => {
      renderDetail({ data: matchedRecord });
      expect(screen.getByText("All 2 line items matched successfully.")).toBeDefined();
    });

    it("renders line items comparison table", () => {
      renderDetail({ data: matchedRecord });
      expect(screen.getByText("Line items comparison")).toBeDefined();
      expect(screen.getByText("DVZA00677")).toBeDefined();
      expect(screen.getByText("DVPU00316")).toBeDefined();
    });

    it("does not show discrepancies section when empty", () => {
      renderDetail({ data: matchedRecord });
      expect(screen.queryByText("Discrepancies")).toBeNull();
    });

    it("renders related documents via LinkedRecordsCard", () => {
      renderDetail({ data: matchedRecord });
      expect(screen.getAllByText(/PO-105539/).length).toBeGreaterThan(0);
      expect(screen.getAllByText(/GR-200145/).length).toBeGreaterThan(0);
    });

    it("hides ActionPanel when matched (no actions needed)", () => {
      renderDetail({ data: matchedRecord, onCreateBill: () => {}, onUpdatePO: () => {} });
      expect(screen.queryByText("Create purchase bill")).toBeNull();
      expect(screen.queryByRole("button", { name: "Update PO" })).toBeNull();
    });

    it("renders activity timeline", () => {
      renderDetail({ data: matchedRecord });
      expect(screen.getByText("Activity")).toBeDefined();
    });
  });

  describe("score color coding", () => {
    it("shows green for scores >= 90", () => {
      renderDetail({ data: matchedRecord });
      const score = screen.getByText(/100% Matched/);
      expect(score.className).toContain("green");
    });

    it("shows yellow for scores 70-89", () => {
      renderDetail({ data: partialMatchRecord });
      const score = screen.getByText(/75% Partial Match/);
      expect(score.className).toContain("yellow");
    });

    it("shows red for scores < 70", () => {
      renderDetail({ data: lowScoreRecord });
      const score = screen.getByText(/50% Mismatch/);
      expect(score.className).toContain("destructive");
    });
  });

  describe("partial match state", () => {
    it("renders discrepancies", () => {
      renderDetail({ data: partialMatchRecord });
      expect(screen.getByText("Discrepancies")).toBeDefined();
      expect(screen.getByText(/PRICE OVER PO/)).toBeDefined();
      expect(screen.getByText(/Price mismatch for SS26OAL1144/)).toBeDefined();
    });

    it("shows ActionPanel with action buttons when partial match", async () => {
      const user = userEvent.setup();
      const onCreateBill = vi.fn();
      const onUpdatePO = vi.fn();

      renderDetail({ data: partialMatchRecord, onCreateBill, onUpdatePO });

      // ActionPanel renders buttons
      expect(screen.getByRole("button", { name: "Create purchase bill" })).toBeDefined();
      expect(screen.getByRole("button", { name: "Update PO" })).toBeDefined();

      await user.click(screen.getByRole("button", { name: "Create purchase bill" }));
      expect(onCreateBill).toHaveBeenCalled();

      await user.click(screen.getByRole("button", { name: "Update PO" }));
      expect(onUpdatePO).toHaveBeenCalled();
    });

    it("shows variance colors in line items", () => {
      renderDetail({ data: partialMatchRecord });
      expect(screen.getByText("Price mismatch")).toBeDefined();
      expect(screen.getByText("+1.4%")).toBeDefined();
    });
  });

  describe("processing state", () => {
    it("shows processing empty state", () => {
      renderDetail({ data: processingRecord });
      expect(screen.getByText(/Processing invoice/)).toBeDefined();
    });

    it("hides DescriptionCard during processing", () => {
      renderDetail({ data: processingRecord });
      expect(screen.queryByText("NEW-001")).toBeNull();
    });

    it("hides line items and discrepancies when processing", () => {
      renderDetail({ data: processingRecord });
      expect(screen.queryByText("Line items comparison")).toBeNull();
      expect(screen.queryByText("Discrepancies")).toBeNull();
    });

    it("auto-polls onRefresh at interval", () => {
      vi.useFakeTimers();
      const onRefresh = vi.fn();

      renderDetail({ data: processingRecord, onRefresh, refreshInterval: 3000 });

      expect(onRefresh).not.toHaveBeenCalled();
      vi.advanceTimersByTime(3000);
      expect(onRefresh).toHaveBeenCalledTimes(1);
      vi.advanceTimersByTime(3000);
      expect(onRefresh).toHaveBeenCalledTimes(2);

      vi.useRealTimers();
    });

    it("does not poll when status is not processing", () => {
      vi.useFakeTimers();
      const onRefresh = vi.fn();

      renderDetail({ data: matchedRecord, onRefresh, refreshInterval: 3000 });

      vi.advanceTimersByTime(10000);
      expect(onRefresh).not.toHaveBeenCalled();

      vi.useRealTimers();
    });
  });

  it("matches snapshot (matched)", () => {
    const { container } = renderDetail({ data: matchedRecord });
    expect(container.innerHTML).toMatchSnapshot();
  });

  it("matches snapshot (partial match)", () => {
    const { container } = renderDetail({
      data: partialMatchRecord,
      onCreateBill: () => {},
      onUpdatePO: () => {},
    });
    expect(container.innerHTML).toMatchSnapshot();
  });
});
