import type * as React from "react";

// ============================================================================
// STATUS TYPES
// ============================================================================

/**
 * Reconciliation matching status.
 */
export type ReconciliationStatus =
  | "processing"
  | "matched"
  | "partial_match"
  | "mismatch"
  | "error";

/**
 * Severity level for a detected discrepancy.
 */
export type DiscrepancySeverity = "warning" | "error";

/**
 * Status of an individual line item in the three-way comparison.
 */
export type LineItemStatus = "matched" | "price_mismatch" | "qty_mismatch" | "missing";

// ============================================================================
// LIST PAGE
// ============================================================================

/**
 * A single row in the reconciliation list table.
 */
export interface ReconciliationListItem {
  id: string;
  invoiceNumber: string;
  supplier: string;
  status: ReconciliationStatus;
  matchScore: number;
  totalAmount: number;
  currency: string;
  date: Date | string;
  /** Optional link to the auto-generated purchase invoice. */
  createdInvoice?: { label: string; href: string };
}

// ============================================================================
// DETAIL PAGE — NESTED DATA
// ============================================================================

/**
 * A step in the processing pipeline (upload → extract → match).
 */
export interface ProcessingStep {
  id: string;
  label: string;
  status: "completed" | "in_progress" | "pending";
  timestamp?: Date | string;
}

/**
 * A detected discrepancy between matched documents.
 */
export interface Discrepancy {
  id: string;
  severity: DiscrepancySeverity;
  category: string;
  message: string;
  resolved: boolean;
}

/**
 * A single row in the three-way line-item comparison table (read-only).
 */
export interface LineItemComparison {
  lineNumber: number;
  product: string;
  status: LineItemStatus;
  invoiceQty: number;
  poQty: number;
  grQty: number;
  qtyVariance: number;
  invoicePrice: number;
  poPrice: number;
  priceVariance: number;
  currency: string;
}

/**
 * A related document (source PO/GR or auto-generated bill).
 */
export interface RelatedDocument {
  id: string;
  type: string;
  label: string;
  status: string;
  statusVariant?: "default" | "success" | "warning" | "error" | "neutral";
  autoGenerated: boolean;
  href: string;
}

// ============================================================================
// DETAIL PAGE — RECORD
// ============================================================================

/**
 * Full reconciliation record for the detail page.
 */
export interface ReconciliationRecord {
  id: string;
  invoiceNumber: string;
  status: ReconciliationStatus;
  matchScore: number;
  supplier: string;
  totalAmount: number;
  currency: string;
  invoiceDate: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
  summary: string;
  processingSteps: ProcessingStep[];
  discrepancies: Discrepancy[];
  lineItems: LineItemComparison[];
  relatedDocuments: RelatedDocument[];
}

// ============================================================================
// COMPONENT PROPS
// ============================================================================

/**
 * Props for the ReconciliationList component.
 */
export interface ReconciliationListProps {
  /** List of reconciliation records to display. */
  items: ReconciliationListItem[];
  /** Called when a row is clicked. */
  onItemClick?: (item: ReconciliationListItem) => void;
  /** Called when a file is uploaded via the dialog. Omit to hide the upload dialog. */
  onUpload?: (file: File) => void;
  /** Controlled open state for the upload dialog. */
  uploadOpen?: boolean;
  /** Called when the upload dialog open state changes. */
  onUploadOpenChange?: (open: boolean) => void;
  /** Override props for the upload dialog (title, accept, etc.). */
  uploadDialogProps?: {
    title?: string;
    description?: string;
    accept?: string;
    uploadLabel?: string;
  };
  /** Custom empty state when no items. */
  emptyState?: React.ReactNode;
  /** Show skeleton loading state. */
  loading?: boolean;
  /** Additional CSS classes on the root. */
  className?: string;
}

/**
 * Props for the ReconciliationDetail component.
 */
export interface ReconciliationDetailProps {
  /** Full reconciliation record. */
  data: ReconciliationRecord;
  /** "Create Purchase Bill" action. Omit to hide. */
  onCreateBill?: () => void;
  /** "Update PO" action. Omit to hide. */
  onUpdatePO?: () => void;
  /** Called on polling interval while status is "processing". */
  onRefresh?: () => void;
  /** Polling interval in ms while processing (default 5000). */
  refreshInterval?: number;
  /** Additional custom action buttons. */
  actions?: React.ReactNode;
  /** Additional CSS classes on the root. */
  className?: string;
}

// ============================================================================
// STATUS HELPERS
// ============================================================================

/** Maps ReconciliationStatus to Badge variant. */
export const statusBadgeVariant: Record<
  ReconciliationStatus,
  "default" | "success" | "warning" | "error"
> = {
  processing: "default",
  matched: "success",
  partial_match: "warning",
  mismatch: "error",
  error: "error",
};

/** Maps ReconciliationStatus to a human-readable label. */
export const statusLabel: Record<ReconciliationStatus, string> = {
  processing: "Processing",
  matched: "Matched",
  partial_match: "Partial Match",
  mismatch: "Mismatch",
  error: "Error",
};

/** Maps LineItemStatus to a Badge variant. */
export const lineItemBadgeVariant: Record<LineItemStatus, "success" | "warning" | "error"> = {
  matched: "success",
  price_mismatch: "warning",
  qty_mismatch: "warning",
  missing: "error",
};

/** Maps LineItemStatus to a human-readable label. */
export const lineItemStatusLabel: Record<LineItemStatus, string> = {
  matched: "Matched",
  price_mismatch: "Price mismatch",
  qty_mismatch: "Qty mismatch",
  missing: "Missing",
};
