import type * as React from "react";
import type { FieldConfig } from "../description-card/types";

// ============================================================================
// STATUS CONFIG
// ============================================================================

/**
 * Consumer-provided status configuration.
 * Defines how the component interprets and displays status values.
 */
export interface StatusConfig {
  /** Status value that means "still processing" — shows loading state. */
  processingStatus: string;
  /** Status value that means "failed" — shows error state. */
  errorStatus: string;
  /** Statuses where action buttons should be hidden (e.g. resolved or processing). */
  hideActionsForStatuses?: string[];
  /** Maps status values to badge variants. */
  badgeVariantMap: Record<string, string>;
  /** Maps status values to human-readable labels. */
  labelMap: Record<string, string>;
}

/**
 * A tab definition for the list filter.
 */
export interface StatusTab {
  /** Status key to filter by. Use "all" to show everything. */
  key: string;
  /** Tab display label. */
  label: string;
}

// ============================================================================
// SEVERITY
// ============================================================================

/**
 * Severity level for a detected discrepancy.
 */
export type DiscrepancySeverity = "warning" | "error";

// ============================================================================
// LIST PAGE
// ============================================================================

/**
 * A single row in the reconciliation list table.
 */
export interface ReconciliationListItem {
  id: string;
  status: string;
  /** All display fields — rendered via list table columns. */
  data: Record<string, unknown>;
}

// ============================================================================
// DETAIL PAGE — NESTED DATA
// ============================================================================

/**
 * A step in the processing pipeline.
 */
export interface ProcessingStep {
  id: string;
  label: string;
  status: "completed" | "in_progress" | "pending";
  timestamp?: Date | string;
}

/**
 * A detected discrepancy between matched documents.
 */
export interface Discrepancy {
  id: string;
  severity: DiscrepancySeverity;
  category: string;
  message: string;
  resolved: boolean;
}

/**
 * Column type for the line items comparison table.
 */
export type LineItemColumnType = "text" | "number" | "badge" | "money" | "variance";

/**
 * A single column definition for the line items table.
 */
export interface LineItemColumn {
  /** Key path to the value in each line item row. */
  key: string;
  /** Column header text. */
  header: string;
  /** Rendering type. Default: "text". */
  type?: LineItemColumnType;
  /** Column alignment. Default: "left". */
  align?: "left" | "right";
  /** Type-specific configuration. */
  meta?: {
    /** Badge variant map for "badge" type columns. */
    badgeVariantMap?: Record<string, string>;
    /** Key path to the currency code in the row, for "money" type columns. */
    currencyKey?: string;
  };
}

/**
 * A related document.
 */
export interface RelatedDocument {
  id: string;
  type: string;
  label: string;
  status: string;
  statusVariant?: "default" | "success" | "warning" | "error" | "neutral";
  autoGenerated: boolean;
  href: string;
}

// ============================================================================
// DETAIL PAGE — RECORD
// ============================================================================

/**
 * Full reconciliation record for the detail page.
 */
export interface ReconciliationRecord {
  id: string;
  status: string;
  matchScore: number;
  /** Generic data bag — DescriptionCard reads from this via field keys. */
  data: Record<string, unknown>;
  summary: string;
  processingSteps: ProcessingStep[];
  discrepancies: Discrepancy[];
  /** Generic line items — column config defines how to render each field. */
  lineItems: Record<string, unknown>[];
  relatedDocuments: RelatedDocument[];
}

// ============================================================================
// COMPONENT PROPS
// ============================================================================

/**
 * Column definition for the list table.
 */
export interface ListColumn {
  /** Key path to the value in the item's `data` bag. Use "status" or "matchScore" for top-level fields. */
  key: string;
  /** Column header text. */
  header: string;
  /** Rendering type. Default: "text". */
  type?: "text" | "number" | "badge" | "money" | "score" | "date" | "link";
  /** Column alignment. Default: "left". */
  align?: "left" | "right";
  /** Truncate cell text with ellipsis. */
  truncate?: boolean;
  /** Type-specific configuration. */
  meta?: {
    /** Badge variant map for "badge" type columns. */
    badgeVariantMap?: Record<string, string>;
    /** Label map for "badge" type columns (maps value to display text). */
    labelMap?: Record<string, string>;
    /** Key path to the currency code, for "money" type columns. */
    currencyKey?: string;
    /** Key path to the href, for "link" type columns. */
    hrefKey?: string;
    /** Status value that should show "—" instead of a number, for "score" type. */
    dashForStatus?: string;
  };
}

/**
 * Props for the ReconciliationList component.
 */
export interface ReconciliationListProps {
  /** List of reconciliation records to display. */
  items: ReconciliationListItem[];
  /** Status configuration — badge variants, labels, behavior keys. */
  statusConfig: StatusConfig;
  /** Tab definitions for status filtering. */
  tabs: StatusTab[];
  /** Column definitions for the list table. */
  columns: ListColumn[];
  /** Called when a row is clicked. */
  onItemClick?: (item: ReconciliationListItem) => void;
  /** Called when a file is uploaded via the dialog. Omit to hide the upload dialog. */
  onUpload?: (file: File) => void;
  /** Controlled open state for the upload dialog. */
  uploadOpen?: boolean;
  /** Called when the upload dialog open state changes. */
  onUploadOpenChange?: (open: boolean) => void;
  /** Override props for the upload dialog (title, accept, etc.). */
  uploadDialogProps?: {
    title?: string;
    description?: string;
    accept?: string;
    uploadLabel?: string;
  };
  /** Custom empty state when no items. */
  emptyState?: React.ReactNode;
  /** Show skeleton loading state. */
  loading?: boolean;
  /** Additional CSS classes on the root. */
  className?: string;
}

/**
 * Props for the ReconciliationDetail component.
 */
export interface ReconciliationDetailProps {
  /** Full reconciliation record. */
  data: ReconciliationRecord;
  /** Status configuration. */
  statusConfig: StatusConfig;
  /** Title for the match result section. */
  title?: string;
  /** DescriptionCard field configuration for the match result section. */
  fields: FieldConfig[];
  /** Column configuration for the line items comparison table. */
  lineItemColumns: LineItemColumn[];
  /** Primary create action. Omit to hide. */
  onCreate?: () => void;
  /** Label for the create action button. */
  createLabel?: string;
  /** Primary update action. Omit to hide. */
  onUpdate?: () => void;
  /** Label for the update action button. */
  updateLabel?: string;
  /** Called on polling interval while status is processing. */
  onRefresh?: () => void;
  /** Polling interval in ms while processing (default 5000). */
  refreshInterval?: number;
  /** Label for the retry action shown in error state. */
  retryLabel?: string;
  /** Additional custom action buttons. */
  actions?: React.ReactNode;
  /** Additional CSS classes on the root. */
  className?: string;
}
