/**
 * Generates self-contained font CSS from fontsource packages.
 *
 * - Reads @font-face declarations from @fontsource-variable/geist and inter
 * - Copies woff2 files to src/assets/fonts/
 * - Outputs src/assets/fonts.generated.css with rewritten url() paths
 *
 * Run manually: `node scripts/generate-fonts.mjs`
 * The output is committed to the repo so CI doesn't need to re-run this.
 */
import { readFileSync, writeFileSync, mkdirSync, cpSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const assetsDir = resolve(import.meta.dirname, "../src/assets");
const fontsDir = resolve(assetsDir, "fonts");

// Clean and recreate fonts directory
rmSync(fontsDir, { recursive: true, force: true });
mkdirSync(fontsDir, { recursive: true });

const FONT_PACKAGES = ["@fontsource-variable/geist", "@fontsource-variable/inter"];

let css = "/* Auto-generated by scripts/generate-fonts.mjs — do not edit manually. */\n\n";

for (const pkg of FONT_PACKAGES) {
  const pkgDir = dirname(require.resolve(`${pkg}/package.json`));
  const pkgCss = readFileSync(resolve(pkgDir, "index.css"), "utf8");

  // Copy woff2 files
  cpSync(resolve(pkgDir, "files"), fontsDir, { recursive: true });

  // Rewrite url(./files/...) → url(./fonts/...)
  css += pkgCss.replace(/url\(\.\/files\//g, "url(./fonts/") + "\n";
}

writeFileSync(resolve(assetsDir, "fonts.generated.css"), css);

console.log("✓ src/assets/fonts.generated.css generated");
console.log(`✓ woff2 files copied to src/assets/fonts/`);
