/**
 * Generates self-contained font CSS from fontsource packages.
 *
 * - Scans packages/core/package.json for @fontsource-variable/* dependencies
 * - Reads @font-face declarations from each package
 * - Copies woff2 files to src/assets/fonts/
 * - Outputs src/assets/fonts.generated.css with rewritten url() paths
 *
 * Run manually: `node scripts/generate-fonts.mjs`
 * The output is committed to the repo so CI doesn't need to re-run this.
 */
import { readFileSync, writeFileSync, mkdirSync, cpSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const assetsDir = resolve(import.meta.dirname, "../src/assets");
const fontsDir = resolve(assetsDir, "fonts");

/**
 * Scan package.json for @fontsource-variable/* dependencies.
 */
const pkgJson = JSON.parse(readFileSync(resolve(import.meta.dirname, "../package.json"), "utf8"));
const FONT_PACKAGES = Object.keys(pkgJson.dependencies || {}).filter((name) =>
  name.startsWith("@fontsource-variable/"),
);

/**
 * Clean output directory before generating new files
 */
rmSync(fontsDir, { recursive: true, force: true });
mkdirSync(fontsDir, { recursive: true });

/**
 * For each font package: read CSS, copy woff2 files, rewrite url() paths, and append to output CSS
 */
const generatedCSS = FONT_PACKAGES.reduce((css, pkg) => {
  const pkgDir = dirname(require.resolve(`${pkg}/package.json`));
  const pkgCss = readFileSync(resolve(pkgDir, "index.css"), "utf8");

  // Copy woff2 files
  cpSync(resolve(pkgDir, "files"), fontsDir, { recursive: true });

  // Rewrite url(./files/...) → url(./fonts/...)
  return css + pkgCss.replace(/url\(\.\/files\//g, "url(./fonts/") + "\n";
}, "/* Auto-generated by scripts/generate-fonts.mjs — do not edit manually. */\n\n");

writeFileSync(resolve(assetsDir, "fonts.generated.css"), generatedCSS);

console.log("✓ src/assets/fonts.generated.css generated");
console.log(`✓ woff2 files copied to src/assets/fonts/`);
