import {
  defineResource,
  Layout,
  Button,
  ReconciliationList,
  ReconciliationDetail,
  useParams,
  useNavigate,
} from "@tailor-platform/app-shell";
import type { ReconciliationListProps, ReconciliationDetailProps } from "@tailor-platform/app-shell";

type ReconciliationListItem = ReconciliationListProps["items"][number];
type ReconciliationRecord = ReconciliationDetailProps["data"];
import { useState, useEffect } from "react";

// Inline upload icon to avoid direct lucide-react dependency in app-module
const UploadIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="16"
    height="16"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="17 8 12 3 7 8" />
    <line x1="12" y1="3" x2="12" y2="15" />
  </svg>
);

// 🧪 Dummy Data: Reconciliation list items
const demoListItems: ReconciliationListItem[] = [
  {
    id: "1",
    invoiceNumber: "26TKC-00200",
    supplier: "CADICA Tekstil VE Tic. Ltd. Sti.",
    status: "matched",
    matchScore: 100,
    totalAmount: 7854.01,
    currency: "USD",
    date: new Date("2026-04-07"),
    createdInvoice: { label: "PI-2026-00371", href: "#" },
  },
  {
    id: "2",
    invoiceNumber: "SS26-0522",
    supplier: "Karmen Deri Urunleri Sanayi ve Ticaret A.S.",
    status: "partial_match",
    matchScore: 75,
    totalAmount: 157990.0,
    currency: "USD",
    date: new Date("2026-04-07"),
  },
  {
    id: "3",
    invoiceNumber: "DT26010026",
    supplier: "Un-Available Co., Ltd.",
    status: "partial_match",
    matchScore: 88,
    totalAmount: 621.37,
    currency: "USD",
    date: new Date("2026-04-07"),
  },
  {
    id: "4",
    invoiceNumber: "INV-2026-0401",
    supplier: "Acme Manufacturing Ltd.",
    status: "mismatch",
    matchScore: 45,
    totalAmount: 23450.0,
    currency: "USD",
    date: new Date("2026-04-06"),
  },
  {
    id: "5",
    invoiceNumber: "INV-2026-0399",
    supplier: "Global Textiles Inc.",
    status: "processing",
    matchScore: 0,
    totalAmount: 5200.0,
    currency: "USD",
    date: new Date("2026-04-08"),
  },
  {
    id: "6",
    invoiceNumber: "INV-2026-0412",
    supplier: "Sunrise Leather Co.",
    status: "error",
    matchScore: 0,
    totalAmount: 8900.0,
    currency: "USD",
    date: new Date("2026-04-09"),
  },
];

// 🧪 Dummy Data: Full records by ID
const recordsById: Record<string, ReconciliationRecord> = {
  "1": {
    id: "1",
    invoiceNumber: "26TKC-00200",
    status: "matched",
    matchScore: 100,
    supplier: "CADICA Tekstil VE Tic. Ltd. Sti.",
    totalAmount: 7854.01,
    currency: "USD",
    invoiceDate: new Date("2026-03-04"),
    createdAt: new Date("2026-04-07"),
    updatedAt: new Date("2026-04-07"),
    summary: "All 2 line items matched successfully.",
    processingSteps: [
      {
        id: "s1",
        label: "Job requested — 26TKC-00200.pdf uploaded by Admin User",
        status: "completed",
        timestamp: new Date("2026-04-07T19:20:33"),
      },
      {
        id: "s2",
        label: "Extraction started — invoice-extraction-schema-v2",
        status: "completed",
        timestamp: new Date("2026-04-07T19:20:35"),
      },
      {
        id: "s3",
        label: "Extraction completed — 2 line items, $7,854.01 total, supplier CADICA Tekstil",
        status: "completed",
        timestamp: new Date("2026-04-07T19:21:17"),
      },
      {
        id: "s4",
        label: "Three-way matching — matched against PO-105539",
        status: "completed",
        timestamp: new Date("2026-04-07T19:21:17"),
      },
      {
        id: "s5",
        label: "Job completed — 100% match, all items verified",
        status: "completed",
        timestamp: new Date("2026-04-07T19:21:42"),
      },
    ],
    discrepancies: [],
    lineItems: [
      {
        lineNumber: 1,
        product: "DVZA00677",
        status: "matched",
        invoiceQty: 35700,
        poQty: 35700,
        grQty: 35700,
        qtyVariance: 0,
        invoicePrice: 0.22,
        poPrice: 0.22,
        priceVariance: 0,
        currency: "USD",
      },
      {
        lineNumber: 2,
        product: "DVPU00316",
        status: "matched",
        invoiceQty: 1,
        poQty: 1,
        grQty: 1,
        qtyVariance: 0,
        invoicePrice: 0.01,
        poPrice: 0.01,
        priceVariance: 0,
        currency: "USD",
      },
    ],
    relatedDocuments: [
      {
        id: "po-1",
        type: "purchase_order",
        label: "PO-105539",
        status: "Approved",
        statusVariant: "success",
        autoGenerated: false,
        href: "#",
      },
      {
        id: "gr-1",
        type: "goods_receipt",
        label: "GR-200145",
        status: "Received",
        statusVariant: "success",
        autoGenerated: false,
        href: "#",
      },
      {
        id: "pi-1",
        type: "purchase_invoice",
        label: "PI-2026-00371",
        status: "Draft",
        statusVariant: "warning",
        autoGenerated: true,
        href: "#",
      },
    ],
  },
  "2": {
    id: "2",
    invoiceNumber: "SS26-0522",
    status: "partial_match",
    matchScore: 75,
    supplier: "Karmen Deri Urunleri Sanayi ve Ticaret A.S.",
    totalAmount: 157990.0,
    currency: "USD",
    invoiceDate: new Date("2026-07-03"),
    createdAt: new Date("2026-04-07"),
    updatedAt: new Date("2026-04-07"),
    summary: "0/2 line items matched. 2 price discrepancies.",
    processingSteps: [
      {
        id: "s1",
        label: "Job requested — 2026-03-08_Karmen Deri_SS26-0522.pdf uploaded by Admin User",
        status: "completed",
        timestamp: new Date("2026-04-07T19:21:08"),
      },
      {
        id: "s2",
        label: "Extraction started — invoice-extraction-schema-v2",
        status: "completed",
        timestamp: new Date("2026-04-07T19:21:08"),
      },
      {
        id: "s3",
        label: "Extraction completed — 2 line items, $157,990 total, supplier Karmen Leather (Turkey)",
        status: "completed",
        timestamp: new Date("2026-04-07T19:21:17"),
      },
      {
        id: "s4",
        label: "Three-way matching — matched against PO-105539, PO-105541",
        status: "completed",
        timestamp: new Date("2026-04-07T19:21:17"),
      },
      {
        id: "s5",
        label: "Job completed — 75% match, 2 discrepancies found",
        status: "completed",
        timestamp: new Date("2026-04-07T19:21:42"),
      },
    ],
    discrepancies: [
      {
        id: "d1",
        severity: "warning",
        category: "Price over PO",
        message: "SS26OAL1144: Invoice $370, PO $365",
        resolved: false,
      },
      {
        id: "d2",
        severity: "error",
        category: "Qty mismatch",
        message: "SS26OAL1144 (line 2): Invoice 10, PO 427",
        resolved: false,
      },
    ],
    lineItems: [
      {
        lineNumber: 1,
        product: "SS26OAL1144",
        status: "price_mismatch",
        invoiceQty: 417,
        poQty: 427,
        grQty: 427,
        qtyVariance: 0,
        invoicePrice: 370,
        poPrice: 365,
        priceVariance: 1.4,
        currency: "USD",
      },
      {
        lineNumber: 2,
        product: "SS26OAL1144",
        status: "price_mismatch",
        invoiceQty: 10,
        poQty: 427,
        grQty: 427,
        qtyVariance: 0,
        invoicePrice: 370,
        poPrice: 365,
        priceVariance: 1.4,
        currency: "USD",
      },
    ],
    relatedDocuments: [
      {
        id: "po-2",
        type: "purchase_order",
        label: "PO-105539",
        status: "Approved",
        statusVariant: "success",
        autoGenerated: false,
        href: "#",
      },
      {
        id: "gr-2",
        type: "goods_receipt",
        label: "GR-200300",
        status: "Received",
        statusVariant: "success",
        autoGenerated: false,
        href: "#",
      },
    ],
  },
  "4": {
    id: "4",
    invoiceNumber: "INV-2026-0401",
    status: "mismatch",
    matchScore: 45,
    supplier: "Acme Manufacturing Ltd.",
    totalAmount: 23450.0,
    currency: "USD",
    invoiceDate: new Date("2026-04-01"),
    createdAt: new Date("2026-04-06"),
    updatedAt: new Date("2026-04-06"),
    summary: "0/2 line items matched. 1 quantity mismatch, 1 missing item.",
    processingSteps: [
      {
        id: "s1",
        label: "Job requested — INV-2026-0401.pdf uploaded by Admin User",
        status: "completed",
        timestamp: new Date("2026-04-06T14:10:00"),
      },
      {
        id: "s2",
        label: "Extraction started — invoice-extraction-schema-v2",
        status: "completed",
        timestamp: new Date("2026-04-06T14:10:02"),
      },
      {
        id: "s3",
        label: "Extraction completed — 2 line items, $23,450 total, supplier Acme Manufacturing",
        status: "completed",
        timestamp: new Date("2026-04-06T14:10:18"),
      },
      {
        id: "s4",
        label: "Three-way matching — matched against PO-108200",
        status: "completed",
        timestamp: new Date("2026-04-06T14:10:19"),
      },
      {
        id: "s5",
        label: "Job completed — 45% match, 2 discrepancies found",
        status: "completed",
        timestamp: new Date("2026-04-06T14:10:32"),
      },
    ],
    discrepancies: [
      {
        id: "d1",
        severity: "error",
        category: "Qty mismatch",
        message:
          "ACME-BOLT-M10: Invoice qty 5000, PO qty 2500 — invoice claims double the ordered quantity",
        resolved: false,
      },
      {
        id: "d2",
        severity: "error",
        category: "Missing item",
        message: "ACME-NUT-M10: Present on invoice but not found on PO-108200",
        resolved: false,
      },
    ],
    lineItems: [
      {
        lineNumber: 1,
        product: "ACME-BOLT-M10",
        status: "qty_mismatch",
        invoiceQty: 5000,
        poQty: 2500,
        grQty: 2500,
        qtyVariance: 100,
        invoicePrice: 3.5,
        poPrice: 3.5,
        priceVariance: 0,
        currency: "USD",
      },
      {
        lineNumber: 2,
        product: "ACME-NUT-M10",
        status: "missing",
        invoiceQty: 2000,
        poQty: 0,
        grQty: 0,
        qtyVariance: 0,
        invoicePrice: 2.85,
        poPrice: 0,
        priceVariance: 0,
        currency: "USD",
      },
    ],
    relatedDocuments: [
      {
        id: "po-4",
        type: "purchase_order",
        label: "PO-108200",
        status: "Confirmed",
        statusVariant: "success",
        autoGenerated: false,
        href: "#",
      },
      {
        id: "gr-4",
        type: "goods_receipt",
        label: "GR-300100",
        status: "Received",
        statusVariant: "success",
        autoGenerated: false,
        href: "#",
      },
    ],
  },
  "5": {
    id: "5",
    invoiceNumber: "INV-2026-0399",
    status: "processing",
    matchScore: 0,
    supplier: "Global Textiles Inc.",
    totalAmount: 5200.0,
    currency: "USD",
    invoiceDate: new Date("2026-04-08"),
    createdAt: new Date("2026-04-08"),
    updatedAt: new Date("2026-04-08"),
    summary: "",
    processingSteps: [
      {
        id: "s1",
        label: "Job requested — INV-2026-0399.pdf uploaded by Admin User",
        status: "completed",
        timestamp: new Date("2026-04-08T10:00:00"),
      },
      {
        id: "s2",
        label: "Extraction in progress — invoice-extraction-schema-v2",
        status: "in_progress",
      },
      { id: "s3", label: "Three-way matching", status: "pending" },
    ],
    discrepancies: [],
    lineItems: [],
    relatedDocuments: [],
  },
  "6": {
    id: "6",
    invoiceNumber: "INV-2026-0412",
    status: "error",
    matchScore: 0,
    supplier: "Sunrise Leather Co.",
    totalAmount: 8900.0,
    currency: "USD",
    invoiceDate: new Date("2026-04-09"),
    createdAt: new Date("2026-04-09"),
    updatedAt: new Date("2026-04-09"),
    summary: "OCR extraction failed — the uploaded file appears to be corrupted or in an unsupported format.",
    processingSteps: [
      {
        id: "s1",
        label: "Job requested — INV-2026-0412.pdf uploaded by Admin User",
        status: "completed",
        timestamp: new Date("2026-04-09T11:30:00"),
      },
      {
        id: "s2",
        label: "Extraction started — invoice-extraction-schema-v2",
        status: "completed",
        timestamp: new Date("2026-04-09T11:30:02"),
      },
      {
        id: "s3",
        label: "Extraction failed — file appears corrupted or unsupported format",
        status: "completed",
        timestamp: new Date("2026-04-09T11:30:05"),
      },
    ],
    discrepancies: [],
    lineItems: [],
    relatedDocuments: [],
  },
};

// ============================================================================
// SHARED STATE — module-level store for upload simulation
// ============================================================================

// 🧪 Module-level store so state persists across list ↔ detail navigation
let _dynamicRecords: Record<string, ReconciliationRecord> = {};
let _dynamicListItems: ReconciliationListItem[] = [];
let _nextId = 100;
let _listeners: Array<() => void> = [];

function subscribe(fn: () => void) {
  _listeners.push(fn);
  return () => {
    _listeners = _listeners.filter((l) => l !== fn);
  };
}

function notify() {
  for (const fn of _listeners) fn();
}

function useDemoStore() {
  const [, forceUpdate] = useState(0);
  useEffect(() => subscribe(() => forceUpdate((c) => c + 1)), []);
  return { dynamicRecords: _dynamicRecords, dynamicListItems: _dynamicListItems };
}

// 🧪 Dummy Data: simulated matched result after processing completes
function buildMatchedRecord(id: string, fileName: string, uploadTime: Date): ReconciliationRecord {
  return {
    id,
    invoiceNumber: fileName.replace(/\.[^.]+$/, ""),
    status: "matched",
    matchScore: 100,
    supplier: "CADICA Tekstil VE Tic. Ltd. Sti.",
    totalAmount: 7854.01,
    currency: "USD",
    invoiceDate: new Date("2026-03-04"),
    createdAt: uploadTime,
    updatedAt: uploadTime,
    summary: "All 2 line items matched successfully.",
    processingSteps: [
      {
        id: "s1",
        label: `Job requested — ${fileName} uploaded by Admin User`,
        status: "completed",
        timestamp: uploadTime,
      },
      {
        id: "s2",
        label: "Extraction started — invoice-extraction-schema-v2",
        status: "completed",
        timestamp: new Date(uploadTime.getTime() + 2000),
      },
      {
        id: "s3",
        label: "Extraction completed — 2 line items, $7,854.01 total, supplier CADICA Tekstil",
        status: "completed",
        timestamp: new Date(uploadTime.getTime() + 4000),
      },
      {
        id: "s4",
        label: "Three-way matching — matched against PO-105539",
        status: "completed",
        timestamp: new Date(uploadTime.getTime() + 5000),
      },
      {
        id: "s5",
        label: "Job completed — 100% match, all items verified",
        status: "completed",
        timestamp: new Date(uploadTime.getTime() + 6000),
      },
    ],
    discrepancies: [],
    lineItems: [
      {
        lineNumber: 1,
        product: "DVZA00677",
        status: "matched",
        invoiceQty: 35700,
        poQty: 35700,
        grQty: 35700,
        qtyVariance: 0,
        invoicePrice: 0.22,
        poPrice: 0.22,
        priceVariance: 0,
        currency: "USD",
      },
      {
        lineNumber: 2,
        product: "DVPU00316",
        status: "matched",
        invoiceQty: 1,
        poQty: 1,
        grQty: 1,
        qtyVariance: 0,
        invoicePrice: 0.01,
        poPrice: 0.01,
        priceVariance: 0,
        currency: "USD",
      },
    ],
    relatedDocuments: [
      {
        id: "po-1",
        type: "purchase_order",
        label: "PO-105539",
        status: "Approved",
        statusVariant: "success",
        autoGenerated: false,
        href: "#",
      },
      {
        id: "gr-1",
        type: "goods_receipt",
        label: "GR-200145",
        status: "Received",
        statusVariant: "success",
        autoGenerated: false,
        href: "#",
      },
      {
        id: "pi-1",
        type: "purchase_invoice",
        label: "PI-2026-00371",
        status: "Draft",
        statusVariant: "warning",
        autoGenerated: true,
        href: "#",
      },
    ],
  };
}

function addUploadedRecord(file: File): string {
  const id = String(_nextId++);
  const now = new Date();
  const fileName = file.name;

  const processingRecord: ReconciliationRecord = {
    id,
    invoiceNumber: fileName.replace(/\.[^.]+$/, ""),
    status: "processing",
    matchScore: 0,
    supplier: "",
    totalAmount: 0,
    currency: "USD",
    invoiceDate: now,
    createdAt: now,
    updatedAt: now,
    summary: "",
    processingSteps: [
      {
        id: "s1",
        label: `Job requested — ${fileName} uploaded by Admin User`,
        status: "completed",
        timestamp: now,
      },
      {
        id: "s2",
        label: "Extraction in progress — invoice-extraction-schema-v2",
        status: "in_progress",
      },
      { id: "s3", label: "Three-way matching", status: "pending" },
    ],
    discrepancies: [],
    lineItems: [],
    relatedDocuments: [],
  };

  _dynamicRecords = { ..._dynamicRecords, [id]: processingRecord };
  _dynamicListItems = [
    {
      id,
      invoiceNumber: processingRecord.invoiceNumber,
      supplier: "—",
      status: "processing",
      matchScore: 0,
      totalAmount: 0,
      currency: "USD",
      date: now,
    },
    ..._dynamicListItems,
  ];
  notify();

  // Simulate pipeline: after 6s transition to matched
  setTimeout(() => {
    const matched = buildMatchedRecord(id, fileName, now);
    _dynamicRecords = { ..._dynamicRecords, [id]: matched };
    _dynamicListItems = _dynamicListItems.map((item) =>
      item.id === id
        ? {
            ...item,
            status: "matched" as const,
            matchScore: 100,
            supplier: matched.supplier,
            totalAmount: matched.totalAmount,
          }
        : item,
    );
    notify();
  }, 6000);

  return id;
}

// ============================================================================
// LIST PAGE
// ============================================================================

const ReconciliationListPage = () => {
  const navigate = useNavigate();
  const [uploadOpen, setUploadOpen] = useState(false);
  const { dynamicListItems } = useDemoStore();

  const allItems = [...dynamicListItems, ...demoListItems];

  return (
    <Layout>
      <Layout.Header
        title="Invoice Reconciliation"
        actions={[
          <Button key="upload" onClick={() => setUploadOpen(true)}>
            <UploadIcon />
            Upload Invoice
          </Button>,
        ]}
      />
      <Layout.Column>
        <ReconciliationList
          items={allItems}
          onItemClick={(item) => {
            navigate(`/custom-page/reconciliation-demo/${item.id}`);
          }}
          onUpload={(file) => {
            const newId = addUploadedRecord(file);
            setUploadOpen(false);
            navigate(`/custom-page/reconciliation-demo/${newId}`);
          }}
          uploadOpen={uploadOpen}
          onUploadOpenChange={setUploadOpen}
        />
      </Layout.Column>
    </Layout>
  );
};

// ============================================================================
// DETAIL PAGE
// ============================================================================

const ReconciliationDetailPage = () => {
  const { id } = useParams<{ id: string }>();
  const { dynamicRecords } = useDemoStore();

  // Look up in dynamic records first, then static
  const record = id ? (dynamicRecords[id] ?? recordsById[id]) : undefined;

  if (!record) {
    return (
      <Layout>
        <Layout.Header title="Not Found" />
        <Layout.Column>
          <p>No reconciliation record found for ID: {id}</p>
        </Layout.Column>
      </Layout>
    );
  }

  return (
    <ReconciliationDetail
      data={record}
      onCreateBill={() =>
        alert("Create Purchase Bill — navigates to bill form with OCR-extracted data pre-filled")
      }
      onUpdatePO={() => alert("Update PO — navigates to purchase order edit page")}
    />
  );
};

// ============================================================================
// RESOURCE DEFINITIONS
// ============================================================================

const reconciliationDetailResource = defineResource({
  path: ":id",
  meta: { title: "Invoice Match Detail" },
  component: ReconciliationDetailPage,
});

export const reconciliationDemoResource = defineResource({
  path: "reconciliation-demo",
  meta: { title: "Reconciliation Demo" },
  component: ReconciliationListPage,
  subResources: [reconciliationDetailResource],
});
