import {
  defineResource,
  Badge,
  DataTable,
  useDataTable,
  useCollectionVariables,
  createColumnHelper,
  Layout,
  type RowAction,
} from "@tailor-platform/app-shell";
import { useState } from "react";
import { type Product, useProductsQuery } from "./mock-data";

// ---------------------------------------------------------------------------
// Mock metadata (normally generated by app-shell-sdk-plugin)
// ---------------------------------------------------------------------------

const productMetadata = {
  name: "product",
  pluralForm: "products",
  fields: [
    { name: "id", type: "uuid", required: true },
    {
      name: "name",
      type: "string",
      required: true,
      description: "Product name",
    },
    { name: "category", type: "string", required: true },
    { name: "price", type: "number", required: true },
    { name: "stock", type: "number", required: false },
    {
      name: "status",
      type: "enum",
      required: true,
      enumValues: ["Active", "Draft", "Archived"],
    },
  ],
} as const;

// ---------------------------------------------------------------------------
// Columns (using createColumnHelper + inferColumns)
// ---------------------------------------------------------------------------

const { column, inferColumns } = createColumnHelper<Product>();
const infer = inferColumns(productMetadata);

const productColumns = [
  column({
    ...infer("name"),
    render: (row) => <span className="font-medium">{row.name}</span>,
  }),
  column(infer("category")),
  column({
    ...infer("price"),
    render: (row) => `$${row.price.toFixed(2)}`,
  }),
  column({
    ...infer("stock"),
    render: (row) => row.stock.toLocaleString(),
  }),
  column({
    ...infer("status"),
    render: (row) => {
      const variant =
        row.status === "Active"
          ? ("success" as const)
          : row.status === "Draft"
            ? ("outline-warning" as const)
            : ("neutral" as const);
      return <Badge variant={variant}>{row.status}</Badge>;
    },
  }),
];

// ---------------------------------------------------------------------------
// Row actions
// ---------------------------------------------------------------------------

const productRowActions: RowAction<Product>[] = [
  {
    id: "edit",
    label: "Edit",
    onClick: (row) => alert(`Edit: ${row.name}`),
  },
  {
    id: "delete",
    label: "Delete",
    variant: "destructive",
    isDisabled: (row) => row.status === "Active",
    onClick: (row) => alert(`Delete: ${row.name}`),
  },
];

// ---------------------------------------------------------------------------
// Page component
// ---------------------------------------------------------------------------

const DataTableDemoPage = () => {
  const { variables, control } = useCollectionVariables({
    params: { pageSize: 5 },
    tableMetadata: productMetadata,
  });
  const { data, loading } = useProductsQuery(variables);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);

  const table = useDataTable({
    columns: productColumns,
    data: data
      ? {
          rows: data.edges.map((e) => e.node),
          pageInfo: {
            hasNextPage: data.pageInfo.hasNextPage,
            hasPreviousPage: data.pageInfo.hasPreviousPage,
            endCursor: data.pageInfo.endCursor,
            startCursor: data.pageInfo.startCursor,
          },
          total: data.total,
        }
      : undefined,
    loading,
    control,
    rowActions: productRowActions,
    onClickRow: (row) => alert(`Clicked: ${row.name}`),
    onSelectionChange: (ids) => setSelectedIds(ids),
  });

  return (
    <Layout>
      <Layout.Header title="DataTable Demo" />
      <Layout.Column>
        <p className="mb-4 text-muted-foreground">
          DataTable demo with sortable columns, row actions, pagination, and
          multi-select.
        </p>
        <DataTable.Root value={table}>
          <DataTable.Toolbar>
            <DataTable.Filters />
          </DataTable.Toolbar>
          <DataTable.Table />
          <DataTable.Footer>
            <DataTable.Pagination pageSizeOptions={[5, 10, 20]} />
          </DataTable.Footer>
        </DataTable.Root>
        {selectedIds.length > 0 && (
          <p className="mb-2 text-sm font-medium">
            {selectedIds.length} row(s) selected: {selectedIds.join(", ")}
          </p>
        )}
      </Layout.Column>
    </Layout>
  );
};

export const dataTableDemoResource = defineResource({
  path: "data-table-demo",
  meta: {
    title: "DataTable Demo",
  },
  component: DataTableDemoPage,
});
