import {
  defineResource,
  DataTable,
  useDataTable,
  useCollectionVariables,
  createColumnHelper,
  Layout,
  type RowAction,
  type TableFieldName,
  useCollectionURLPersistence,
} from "@tailor-platform/app-shell";
import { useState } from "react";
import { type Product, useProductsQuery } from "./mock-data";

// ---------------------------------------------------------------------------
// Mock metadata (normally generated by app-shell-sdk-plugin)
// ---------------------------------------------------------------------------

const productMetadata = {
  name: "product",
  pluralForm: "products",
  fields: [
    { name: "id", type: "uuid", required: true },
    {
      name: "name",
      type: "string",
      required: true,
      description: "Product name",
    },
    {
      name: "description",
      type: "string",
      required: true,
      description: "Description",
    },
    { name: "category", type: "string", required: true },
    { name: "publishedAt", type: "datetime", required: true },
    { name: "availableOn", type: "date", required: true },
    { name: "restockAt", type: "time", required: true },
    { name: "price", type: "number", required: true },
    { name: "stock", type: "number", required: false },
    {
      name: "status",
      type: "enum",
      required: true,
      enumValues: ["Active", "Draft", "Archived"],
    },
    { name: "tags", type: "string", required: false },
  ],
} as const;

// ---------------------------------------------------------------------------
// Columns (using createColumnHelper + inferColumns)
// ---------------------------------------------------------------------------

const { column, inferColumns } = createColumnHelper<Product>();
const infer = inferColumns(productMetadata);

const productColumns = [
  column({
    ...infer("name"),
    render: (row) => <span className="font-medium">{row.name}</span>,
  }),
  // Demonstrates `truncate: true` — long descriptions are clipped with an
  // ellipsis and the full value is revealed in a `<Tooltip>` on hover.
  // No explicit `accessor` needed: `infer("description")` pins the column
  // `id` to the field name, so the tooltip resolves via `row[col.id]`.
  column({
    ...infer("description"),
    type: "text",
    truncate: true,
  }),
  column(infer("category")),
  column({
    ...infer("price"),
    type: "money",
  }),
  column({
    ...infer("publishedAt"),
    render: (row) => <span className="font-mono text-xs">{row.publishedAt}</span>,
  }),
  column({
    ...infer("availableOn"),
    render: (row) => <span className="font-mono text-xs">{row.availableOn}</span>,
  }),
  column({
    ...infer("restockAt"),
    render: (row) => <span className="font-mono text-xs">{row.restockAt}</span>,
  }),
  column({
    ...infer("stock"),
    type: "number",
  }),
  column({
    ...infer("status"),
    type: "badge",
    typeOptions: {
      badgeVariantMap: {
        Active: "success",
        Draft: "outline-warning",
        Archived: "neutral",
      },
    },
  }),
  column({
    ...infer("tags"),
    type: "badge",
    typeOptions: {
      badgeVariantMap: {
        Premium: "warning",
        Ergonomic: "success",
        Office: "outline-info",
        Wireless: "outline-neutral",
      },
      defaultBadgeVariant: "neutral",
      maxVisible: 2,
    },
  }),
];

// ---------------------------------------------------------------------------
// Row actions
// ---------------------------------------------------------------------------

const productRowActions: RowAction<Product>[] = [
  {
    id: "edit",
    label: "Edit",
    onClick: (row) => alert(`Edit: ${row.name}`),
  },
  {
    id: "delete",
    label: "Delete",
    variant: "destructive",
    isDisabled: (row) => row.status === "Active",
    onClick: (row) => alert(`Delete: ${row.name}`),
  },
];

// ---------------------------------------------------------------------------
// Page component
// ---------------------------------------------------------------------------

const DataTableDemoPage = () => {
  const persistence = useCollectionURLPersistence<TableFieldName<typeof productMetadata>>({
    prefix: "dt1",
  });
  const { variables, control } = useCollectionVariables({
    params: { pageSize: 5 },
    tableMetadata: productMetadata,
    persistence,
  });
  const { data, loading } = useProductsQuery(variables);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);

  const table = useDataTable({
    columns: productColumns,
    data: data
      ? {
          rows: data.edges.map((e) => e.node),
          pageInfo: {
            hasNextPage: data.pageInfo.hasNextPage,
            hasPreviousPage: data.pageInfo.hasPreviousPage,
            endCursor: data.pageInfo.endCursor,
            startCursor: data.pageInfo.startCursor,
          },
          total: data.total,
        }
      : undefined,
    loading,
    control,
    rowActions: productRowActions,
    onClickRow: (row) => alert(`Clicked: ${row.name}`),
    onSelectionChange: (ids) => setSelectedIds(ids),
  });

  return (
    <Layout>
      <Layout.Header title="DataTable Demo" />
      <Layout.Column>
        <p className="mb-4 text-muted-foreground">
          DataTable demo with sortable columns, row actions, pagination, multi-select, and temporal
          filters for datetime, date, and time fields.
        </p>
        <DataTable.Root value={table}>
          <DataTable.Toolbar>
            <DataTable.Filters />
          </DataTable.Toolbar>
          <DataTable.Table />
          <DataTable.Footer>
            <DataTable.Pagination pageSizeOptions={[5, 10, 20]} />
          </DataTable.Footer>
        </DataTable.Root>
        {selectedIds.length > 0 && (
          <p className="mb-2 text-sm font-medium">
            {selectedIds.length} row(s) selected: {selectedIds.join(", ")}
          </p>
        )}
      </Layout.Column>
    </Layout>
  );
};

export const dataTableDemoResource = defineResource({
  path: "data-table-demo",
  meta: {
    title: "DataTable Demo",
  },
  component: DataTableDemoPage,
});
