// GENERATED by docs-kit — do not edit by hand.
import type { AppShellPageProps } from "@tailor-platform/app-shell";

import { DocPage } from "../../../_lib/DocPage";

const Page = () => <DocPage slug="interaction-toast" />;

Page.appShellPageProps = {
  meta: { title: "Toast" },
} satisfies AppShellPageProps;

export default Page;
