import {
  Layout,
  Badge,
  DataTable,
  Pagination,
  useDataTable,
  useCollectionVariables,
  createColumnHelper,
  type CollectionResult,
  type CollectionVariables,
  type RowAction,
  type AppShellPageProps,
} from "@tailor-platform/app-shell";
import { useMemo } from "react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  stock: number;
  status: "Active" | "Draft" | "Archived";
};

// ---------------------------------------------------------------------------
// Mock metadata (normally generated by app-shell-sdk-plugins)
// ---------------------------------------------------------------------------

const productMetadata = {
  name: "product",
  pluralForm: "products",
  fields: [
    { name: "id", type: "uuid", required: true },
    {
      name: "name",
      type: "string",
      required: true,
      description: "Product name",
    },
    { name: "category", type: "string", required: true },
    { name: "price", type: "number", required: true },
    { name: "stock", type: "number", required: false },
    {
      name: "status",
      type: "enum",
      required: true,
      enumValues: ["Active", "Draft", "Archived"],
    },
  ],
} as const;

// ---------------------------------------------------------------------------
// Columns (using createColumnHelper + inferColumns)
// ---------------------------------------------------------------------------

const { column, inferColumns } = createColumnHelper<Product>();
const infer = inferColumns(productMetadata);

const columns = [
  column({
    ...infer("name"),
    render: (row) => <span className="font-medium">{row.name}</span>,
  }),
  column(infer("category")),
  column({
    ...infer("price"),
    render: (row) => `$${row.price.toFixed(2)}`,
  }),
  column({
    ...infer("stock"),
    render: (row) => row.stock.toLocaleString(),
  }),
  column({
    ...infer("status"),
    render: (row) => {
      const variant =
        row.status === "Active"
          ? ("success" as const)
          : row.status === "Draft"
            ? ("outline-warning" as const)
            : ("neutral" as const);
      return <Badge variant={variant}>{row.status}</Badge>;
    },
  }),
];

// ---------------------------------------------------------------------------
// Mock data (CollectionResult format)
// ---------------------------------------------------------------------------

const mockProducts: CollectionResult<Product> = {
  edges: [
    {
      node: {
        id: "p-001",
        name: "Ergonomic Chair",
        category: "Furniture",
        price: 499.99,
        stock: 42,
        status: "Active",
      },
    },
    {
      node: {
        id: "p-002",
        name: "Standing Desk",
        category: "Furniture",
        price: 899.0,
        stock: 15,
        status: "Active",
      },
    },
    {
      node: {
        id: "p-003",
        name: "Mechanical Keyboard",
        category: "Electronics",
        price: 159.99,
        stock: 230,
        status: "Active",
      },
    },
    {
      node: {
        id: "p-004",
        name: "USB-C Hub",
        category: "Electronics",
        price: 79.99,
        stock: 0,
        status: "Draft",
      },
    },
    {
      node: {
        id: "p-005",
        name: "Monitor Arm",
        category: "Accessories",
        price: 129.0,
        stock: 57,
        status: "Active",
      },
    },
    {
      node: {
        id: "p-006",
        name: "Webcam HD",
        category: "Electronics",
        price: 89.99,
        stock: 120,
        status: "Archived",
      },
    },
    {
      node: {
        id: "p-007",
        name: "Desk Lamp",
        category: "Accessories",
        price: 45.0,
        stock: 88,
        status: "Active",
      },
    },
    {
      node: {
        id: "p-008",
        name: "Cable Tray",
        category: "Accessories",
        price: 29.99,
        stock: 200,
        status: "Draft",
      },
    },
  ],
  pageInfo: {
    hasNextPage: false,
    endCursor: null,
    hasPreviousPage: false,
    startCursor: null,
  },
  total: 8,
};

// ---------------------------------------------------------------------------
// Row actions
// ---------------------------------------------------------------------------

const rowActions: RowAction<Product>[] = [
  {
    id: "edit",
    label: "Edit",
    onClick: (row) => alert(`Edit: ${row.name}`),
  },
  {
    id: "delete",
    label: "Delete",
    variant: "destructive",
    isDisabled: (row) => row.status === "Active",
    onClick: (row) => alert(`Delete: ${row.name}`),
  },
];

// ---------------------------------------------------------------------------
// Mock query hook (simulates a real useQuery call)
// ---------------------------------------------------------------------------

function useProductsQuery(_variables: CollectionVariables) {
  // In a real app this would be a GraphQL / REST call that forwards the
  // variables (pagination, sorting, filters) to the server.
  return useMemo(() => ({ data: mockProducts, loading: false }), []);
}

// ---------------------------------------------------------------------------
// Page component
// ---------------------------------------------------------------------------

const ProductsPage = () => {
  const { variables, control } = useCollectionVariables({
    params: { pageSize: 10 },
  });

  const { data, loading } = useProductsQuery(variables);

  const table = useDataTable<Product>({
    columns,
    data,
    loading,
    control,
    rowActions,
    onClickRow: (row) => alert(`Clicked: ${row.name}`),
  });

  return (
    <Layout>
      <Layout.Header title="Products" />
      <Layout.Column>
        <p className="mb-4 text-muted-foreground">
          DataTable demo with sortable columns, row actions, and pagination.
        </p>
        <DataTable.Provider value={table}>
          <DataTable.Root>
            <DataTable.Headers />
            <DataTable.Body />
          </DataTable.Root>
          <Pagination />
        </DataTable.Provider>
      </Layout.Column>
    </Layout>
  );
};

ProductsPage.appShellPageProps = {
  meta: {
    title: "Products",
  },
} satisfies AppShellPageProps;

export default ProductsPage;
