import { describe, it, expect } from "vitest";
import {
  extractParams,
  generateParamsType,
  generateTypedRoutesCode,
} from "./typed-routes-gen";
import type { PageFile } from "./scanner";

// ============================================
// extractParams Tests
// ============================================

describe("extractParams", () => {
  it("returns empty array for static route", () => {
    expect(extractParams("/dashboard")).toEqual([]);
  });

  it("extracts single dynamic parameter", () => {
    expect(extractParams("/orders/:id")).toEqual(["id"]);
  });

  it("extracts multiple dynamic parameters", () => {
    expect(extractParams("/orders/:orderId/items/:itemId")).toEqual([
      "orderId",
      "itemId",
    ]);
  });

  it("handles root path", () => {
    expect(extractParams("/")).toEqual([]);
  });

  it("stops at query string for dynamic params", () => {
    // Note: query string is handled at runtime, not in type generation
    expect(extractParams("/orders/:id?tab=details")).toEqual(["id"]);
  });

  it("extracts catch-all parameter", () => {
    expect(extractParams("/docs/*slug")).toEqual(["slug"]);
  });

  it("extracts both dynamic and catch-all parameters", () => {
    expect(extractParams("/org/:orgId/docs/*slug")).toEqual(["orgId", "slug"]);
  });
});

// ============================================
// generateParamsType Tests
// ============================================

describe("generateParamsType", () => {
  it("returns empty object for no params", () => {
    expect(generateParamsType([])).toBe("{}");
  });

  it("generates single param type", () => {
    expect(generateParamsType(["id"])).toBe("{ id: string }");
  });

  it("generates multiple params type", () => {
    expect(generateParamsType(["orderId", "itemId"])).toBe(
      "{ orderId: string; itemId: string }",
    );
  });
});

// ============================================
// generateTypedRoutesCode Tests
// ============================================

describe("generateTypedRoutesCode", () => {
  it("generates code for empty pages array", () => {
    const code = generateTypedRoutesCode([]);
    expect(code).toContain("export type GeneratedRouteParams = {");
    expect(code).toContain("};");
    expect(code).toContain(
      'import { createTypedPaths } from "@tailor-platform/app-shell"',
    );
    expect(code).toContain(
      "export const paths = createTypedPaths<GeneratedRouteParams>();",
    );
  });

  it("generates code for static routes", () => {
    const pages: PageFile[] = [
      { filePath: "/src/pages/page.tsx", relativePath: "", routePath: "" },
      {
        filePath: "/src/pages/dashboard/page.tsx",
        relativePath: "dashboard",
        routePath: "dashboard",
      },
    ];
    const code = generateTypedRoutesCode(pages);
    expect(code).toContain('"/": {};');
    expect(code).toContain('"/dashboard": {};');
  });

  it("generates code for dynamic routes", () => {
    const pages: PageFile[] = [
      {
        filePath: "/src/pages/orders/[id]/page.tsx",
        relativePath: "orders/[id]",
        routePath: "orders/:id",
      },
    ];
    const code = generateTypedRoutesCode(pages);
    expect(code).toContain('"/orders/:id": { id: string };');
  });

  it("generates code for routes with multiple params", () => {
    const pages: PageFile[] = [
      {
        filePath: "/src/pages/orders/[orderId]/items/[itemId]/page.tsx",
        relativePath: "orders/[orderId]/items/[itemId]",
        routePath: "orders/:orderId/items/:itemId",
      },
    ];
    const code = generateTypedRoutesCode(pages);
    expect(code).toContain(
      '"/orders/:orderId/items/:itemId": { orderId: string; itemId: string };',
    );
  });

  it("generates code for catch-all routes", () => {
    const pages: PageFile[] = [
      {
        filePath: "/src/pages/docs/[...slug]/page.tsx",
        relativePath: "docs/[...slug]",
        routePath: "docs/*slug",
      },
    ];
    const code = generateTypedRoutesCode(pages);
    expect(code).toContain('"/docs/*slug": { slug: string };');
  });

  it("sorts routes alphabetically", () => {
    const pages: PageFile[] = [
      {
        filePath: "/src/pages/z-page/page.tsx",
        relativePath: "z-page",
        routePath: "z-page",
      },
      {
        filePath: "/src/pages/a-page/page.tsx",
        relativePath: "a-page",
        routePath: "a-page",
      },
    ];
    const code = generateTypedRoutesCode(pages);
    const aIndex = code.indexOf('"/a-page"');
    const zIndex = code.indexOf('"/z-page"');
    expect(aIndex).toBeLessThan(zIndex);
  });

  it("includes auto-generated header comment", () => {
    const code = generateTypedRoutesCode([]);
    expect(code).toContain(
      "// Auto-generated by @tailor-platform/app-shell-vite-plugin",
    );
    expect(code).toContain("// Do not edit manually");
  });

  it("includes module augmentation for AppShellRegister", () => {
    const code = generateTypedRoutesCode([]);
    expect(code).toContain('declare module "@tailor-platform/app-shell"');
    expect(code).toContain("interface AppShellRegister");
    expect(code).toContain("routeParams: GeneratedRouteParams;");
  });
});
