// GENERATED by docs-kit — do not edit by hand.
import type { AppShellPageProps } from "@tailor-platform/app-shell";

import { DocPage } from "../../../../_lib/DocPage";

const Page = () => <DocPage slug="guards/pass" />;

Page.appShellPageProps = {
  meta: { title: "pass" },
} satisfies AppShellPageProps;

export default Page;
