name: Add Changeset to Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, labeled]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  add-changeset:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: IzumiSy/deps2changesets@main
