name: packages/core coverage

on:
  push:
    branches:
      - main
    paths:
      - "packages/core/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".octocov.yml"
      - ".github/workflows/packages-core-coverage.yaml"
  pull_request:
    paths:
      - "packages/core/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".octocov.yml"
      - ".github/workflows/packages-core-coverage.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      actions: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          node-version-file: "./package.json"
      - name: Install dependencies
        run: pnpm install
      - name: Collect packages/core coverage
        run: pnpm --filter @tailor-platform/app-shell test:coverage
      - uses: k1LoW/octocov-action@a339ff297f3f6773aad1117d7ef2294fdd46b963 # v1
